image:
  file: Dockerfile
ports:
  - port: 6080
    protocol: "http"

checkoutLocation: work
workspaceLocation: /
tasks:
  - command: |
      echo "Excluding unnecessary files..."
      rm -rf images LICENSE README.md